import Head from 'next/head'
import { Poppins } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Header } from '@/components/header'

const poppins = Poppins({
  weight: ['300', '400', '600', '800'], 
  subsets: ['latin']
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Primus- troca de óleo de serviços </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head> 
      <main className={`${styles.main}`}>
          <Header/>
      </main>
    </>
  )
}
